const points = [
    //world
    {
        name: "main",
        dimensions: [
            {
                type: "overworld",
                points: [
                    {
                        //地名
                        name: "sample",

                        //座標
                        coord: { "x": 0, "z": 0 },

                        //icon画像 default:point
                        icon: "point",

                        //どこまで拡大しても表示するか default:8
                        maxZoom: 6,

                        //どこまで縮小しても表示するか default:0
                        minZoom: 3,

                        //infoウィンドウ(クリックしたら出る)の内容
                        info: "This is a <b>sample</b>",

                        //表示するかどうか
                        visible: false,
                    },
                    //0
                    {
                        name: "マンナ海",
                        coord: { x:-1116, z:-549 },
                        icon: "text",
                        maxZoom: 2,
                        minZoom: 0,
                        info: "世界の真ん中にある大きな海",
                        visible: true,
                    },
                    {
                        name: "ココ・ド・荒野",
                        coord: { x:1117, z:242 },
                        icon: "text",
                        maxZoom: 4,
                        minZoom: 0,
                        info: "やたら大きい乾燥地帯",
                        visible: true,
                    },
                    {
                        name: "アッタ海",
                        coord: { x:1815, z:-1137 },
                        icon: "text",
                        maxZoom: 4,
                        minZoom: 0,
                        info: "温暖な海",
                        visible: true,
                    },
                    {
                        name: "ツメタイ洋",
                        coord: { x:92, z:1731 },
                        icon: "text",
                        maxZoom: 4,
                        minZoom: 0,
                        info: "寒冷で氷山浮かぶ海",
                        visible: true,
                    },
                    {
                        name: "Pランド",
                        coord: { x:-1827, z:1803 },
                        icon: "text",
                        maxZoom: 4,
                        minZoom: 0,
                        info: "大陸大平原の南西部",
                        visible: true,
                    },
                    {
                        name: "アルシア平原",
                        coord: { x:-1434, z:1243 },
                        icon: "text",
                        maxZoom: 4,
                        minZoom: 0,
                        info: "大陸大平原の中央部",
                        visible: true,
                    },
                    {
                        name: "ブラスラント",
                        coord: { x:-1240, z:354 },
                        icon: "text",
                        maxZoom: 4,
                        minZoom: 0,
                        info: "マンナ海南部の大きな半島",
                        visible: true,
                    },
                    {
                        name: "グリセンヌ",
                        coord: { x:-824, z:715 },
                        icon: "text",
                        maxZoom: 4,
                        minZoom: 0,
                        info: "入り江の多い沿岸部",
                        visible: true,
                    },
                    {
                        name: "シッチー地方",
                        coord: { x:216, z:560 },
                        icon: "text",
                        maxZoom: 4,
                        minZoom: 0,
                        info: "大陸の大湿地地帯",
                        visible: true,
                    },
                    {
                        name: "OKプレーン",
                        coord: { x:-2011, z:-953 },
                        icon: "text",
                        maxZoom: 4,
                        minZoom: 0,
                        info: "マンナ海の乾燥した大きな島",
                        visible: true,
                    },
                    {
                        name: "スラム砂漠",
                        coord: { x:-799, z:-1871 },
                        icon: "text",
                        maxZoom: 4,
                        minZoom: 0,
                        info: "マンナ海北の大砂漠地帯",
                        visible: true,
                    },
                    {
                        name: "モルメントバレー",
                        coord: { x:281, z:-1720 },
                        icon: "text",
                        maxZoom: 4,
                        minZoom: 0,
                        info: "広大なメサ地帯",
                        visible: true,
                    },
                    {
                        name: "サパンダ",
                        coord: { x:717, z:-540 },
                        icon: "text",
                        maxZoom: 4,
                        minZoom: 0,
                        info: "大きなサバンナ地帯",
                        visible: true,
                    },
                    {
                        name: "Eジプ島",
                        coord: { x:-1385, z:-1451 },
                        icon: "text",
                        maxZoom: 4,
                        minZoom: 0,
                        info: "乾燥した大きな半島のある島",
                        visible: true,
                    },
                    //2
                    {
                        name: "初期リス平原",
                        coord: { x:262, z:42 },
                        icon: "text",
                        maxZoom: 4,
                        minZoom: 1,
                        info: "初期リスポーンの平原",
                        visible: true,
                    },
                    {
                        name: "大地島",
                        coord: { x:-223, z:-9 },
                        icon: "text",
                        maxZoom: 4,
                        minZoom: 1,
                        info: "都市のある島",
                        visible: true,
                    },
                    {
                        name: "Nao諸島",
                        coord: { x:-1109, z:-390 },
                        icon: "text",
                        maxZoom: 4,
                        minZoom: 1,
                        info: "Naoさんの島々",
                        visible: true,
                    },
                    {
                        name: "シットリ半島",
                        coord: { x:-1278, z:-1115 },
                        icon: "text",
                        maxZoom: 4,
                        minZoom: 1,
                        info: "砂漠の大きな半島",
                        visible: true,
                    },
                    {
                        name: "アラタナ平原",
                        coord: { x:1043, z:-929 },
                        icon: "text",
                        maxZoom: 4,
                        minZoom: 1,
                        info: "小さな平原",
                        visible: true,
                    },
                    {
                        name: "オルカナキア平原",
                        coord: { x:-1023, z:1043 },
                        icon: "text",
                        maxZoom: 4,
                        minZoom: 1,
                        info: "大陸大平原の北部",
                        visible: true,
                    },
                    {
                        name: "シメイ地方",
                        coord: { x:-399, z:1186 },
                        icon: "text",
                        maxZoom: 4,
                        minZoom: 1,
                        info: "鬱蒼とした森林と平原のある地域",
                        visible: true,
                    },
                    {
                        name: "シマ半島",
                        coord: { x:-298, z:1548 },
                        icon: "text",
                        maxZoom: 4,
                        minZoom: 1,
                        info: "白樺の森に覆われた半島",
                        visible: true,
                    },
                    {
                        name: "クロツェニア",
                        coord: { x:-959, z:1543 },
                        icon: "text",
                        maxZoom: 4,
                        minZoom: 1,
                        info: "交通の要所と知られる平原",
                        visible: true,
                    },
                    {
                        name: "九段高原",
                        coord: { x:-179, z:847 },
                        icon: "text",
                        maxZoom: 4,
                        minZoom: 1,
                        info: "大陸を隔てる高山地帯",
                        visible: true,
                    },
                    {
                        name: "九段港湾",
                        coord: { x:145, z:1187 },
                        icon: "text",
                        maxZoom: 4,
                        minZoom: 1,
                        info: "ツメタイ洋北部の大きな湾",
                        visible: true,
                    },
                    {
                        name: "デンス",
                        coord: { x:-1664, z:967 },
                        icon: "text",
                        maxZoom: 4,
                        minZoom: 1,
                        info: "暗い森の沿岸部",
                        visible: true,
                    },
                    {
                        name: "ナラモス",
                        coord: { x:-1297, z:723 },
                        icon: "text",
                        maxZoom: 4,
                        minZoom: 1,
                        info: "花の森と世界樹",
                        visible: true,
                    },
                    {
                        name: "レイランド",
                        coord: { x:558, z:1337 },
                        icon: "text",
                        maxZoom: 4,
                        minZoom: 1,
                        info: "雪山と平原のある地域",
                        visible: true,
                    },
                    {
                        name: "ぬこ台地",
                        coord: { x:353, z:229 },
                        icon: "text",
                        maxZoom: 4,
                        minZoom: 1,
                        info: "小高い丘",
                        visible: true,
                    },
                    {
                        name: "モルチモア島",
                        coord: { "x": -240, "z": -1022 },
                        icon: "waypoint",
                        maxZoom: 8,
                        minZoom: 1,
                        info: "西部開拓時代風の街がある島",
                        visible: true,
                    },
                    {
                        name: "コンロリ島",
                        coord: { x:-604, z:-475 },
                        icon: "waypoint",
                        maxZoom: 8,
                        minZoom: 1,
                        info: "エンチャ本取引所と多くの自動生産設備のある島",
                        visible: true,
                    },
                    {
                        name: "天空回廊",
                        coord: { x:-1795, z:1498 },
                        icon: "waypoint",
                        maxZoom: 8,
                        minZoom: 1,
                        info: "空中に浮く巨大な何か",
                        visible: true,
                    },
                    //3
                    {
                        name: "鶏卵古代文明",
                        coord: { x:-1512, z:1655 },
                        icon: "text",
                        maxZoom: 5,
                        minZoom: 2,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "スイレン湾",
                        coord: { "x": -808, "z": 662 },
                        icon:"text",
                        maxZoom: 8,
                        minZoom: 5,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "初期リス",
                        coord: { "x": 246, "z": -81 },
                        icon: "waypoint",
                        maxZoom: 8,
                        minZoom: 2,
                        info: "初期リス",
                        visible: true,
                    },
                    {
                        name: "大ポンタ島",
                        coord: { "x": -497, "z": 253 },
                        maxZoom: 8,
                        minZoom: 2,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "ヒト島",
                        coord: { "x": -802, "z": -197 },
                        maxZoom: 8,
                        minZoom: 2,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "Nao本島",
                        coord: { "x": -1112, "z": -324 },
                        maxZoom: 8,
                        minZoom: 2,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "アロンシープ島",
                        coord: { "x": -551, "z": -1244 },
                        maxZoom: 8,
                        minZoom: 2,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "デルフォリス号",
                        coord: { "x": -259, "z": 128 },
                        maxZoom: 8,
                        minZoom: 2,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "ポータル",
                        coord: { "x": -225, "z": 1317 },
                        maxZoom: 8,
                        minZoom: 2,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "九段港",
                        coord: { "x": 113, "z": 1139 },
                        maxZoom: 8,
                        minZoom: 2,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "レクト群島",
                        coord: { "x": -1319, "z": -517 },
                        maxZoom: 8,
                        minZoom: 2,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "アラネア島",
                        coord: { "x": -630, "z": -958 },
                        maxZoom: 8,
                        minZoom: 2,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "パンダ国",
                        coord: { "x": 689, "z": -526 },
                        maxZoom: 8,
                        minZoom: 2,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "エーリヒクベルク",
                        coord: { "x": -951, "z": 352 },
                        maxZoom: 8,
                        minZoom: 2,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "オルカナキア共和国連合",
                        coord: { "x": -1182, "z": 866 },
                        maxZoom: 8,
                        minZoom: 2,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "納島",
                        coord: { "x": 269, "z": -257 },
                        maxZoom: 8,
                        minZoom: 2,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "カルハイド",
                        coord: { "x": -191, "z": 37 },
                        maxZoom: 8,
                        minZoom: 2,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "ウルルト",
                        coord: { "x": -297, "z": 612 },
                        maxZoom: 8,
                        minZoom: 2,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "レイラン公領",
                        coord: { "x": 473, "z": 1239 },
                        maxZoom: 8,
                        minZoom: 2,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "中書島",
                        coord: { "x": 485, "z": -1207 },
                        maxZoom: 8,
                        minZoom: 2,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "ニイナハウス",
                        coord: { "x": 1126, "z": -879 },
                        maxZoom: 8,
                        minZoom: 2,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "みやこハウス",
                        coord: { "x": 95, "z": 575 },
                        maxZoom: 8,
                        minZoom: 2,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "スイレンスブール",
                        coord: { "x": -759, "z": 727 },
                        maxZoom: 8,
                        minZoom: 2,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "おしるこ海洋要塞",
                        coord: { "x": -864, "z": -670 },
                        maxZoom: 8,
                        minZoom: 2,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "うまれえき",
                        coord: { "x": 208, "z": 234 },
                        maxZoom: 8,
                        minZoom: 2,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "KOG島",
                        coord: { "x": -1646, "z": -946 },
                        maxZoom: 8,
                        minZoom: 2,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "最果村",
                        coord: { "x": -1943, "z": 1987 },
                        maxZoom: 8,
                        minZoom: 2,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "デンス村",
                        coord: { "x": -1788, "z": 987 },
                        maxZoom: 8,
                        minZoom: 2,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "マルブール",
                        coord: { x:-845, z:1444 },
                        maxZoom: 8,
                        minZoom: 2,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "ドロワーズ",
                        coord: { "x": -233, "z": 1691 },
                        maxZoom: 8,
                        minZoom: 2,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "廃墟",
                        coord: { "x": -1415, "z": 1249 },
                        maxZoom: 8,
                        minZoom: 2,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "クノーテン",
                        coord: { "x": -1644, "z": 240 },
                        maxZoom: 8,
                        minZoom: 2,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "雲の上",
                        coord: { "x": -438, "z": 1894 },
                        maxZoom: 8,
                        minZoom: 2,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "ガンツ",
                        coord: { "x": -1462, "z": 1604 },
                        maxZoom: 8,
                        minZoom: 2,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "罪の塔",
                        coord: { "x": -1593, "z": 1722 },
                        maxZoom: 8,
                        minZoom: 2,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "クゼトガザム",
                        coord: { "x": -488, "z": 996 },
                        maxZoom: 8,
                        minZoom: 2,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "モノリス",
                        coord: { "x": 747, "z": 36 },
                        maxZoom: 8,
                        minZoom: 2,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "May馬牧場",
                        coord: { "x": -660, "z": 859 },
                        maxZoom: 8,
                        minZoom: 2,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "Lihi城",
                        coord: { x:-1637, z:1983 },
                        maxZoom: 8,
                        minZoom: 2,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "世界樹",
                        coord: { x:-1306, z:713 },
                        maxZoom: 8,
                        minZoom: 2,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "銚子島",
                        coord: { x:10, z:-193 },
                        maxZoom: 8,
                        minZoom: 2,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "tppap空中要塞",
                        coord: { x:-24, z:47 },
                        maxZoom: 8,
                        minZoom: 2,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "コオルモット",
                        coord: { x:60, z:1667 },
                        maxZoom: 8,
                        minZoom: 2,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "スライム島",
                        coord: { x:-434, z:-309 },
                        maxZoom: 8,
                        minZoom: 2,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "ネルバヤシスパイラル",
                        coord: { x:-508, z:-138 },
                        maxZoom: 8,
                        minZoom: 2,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "下着海洋プラント",
                        coord: { x:-556, z:110 },
                        maxZoom: 8,
                        minZoom: 2,
                        info: "やたら六角形な海上プラント",
                        visible: true,
                    },
                    {
                        name: "北鈴蘭台島",
                        coord: { x:343, z:-1018 },
                        maxZoom: 8,
                        minZoom: 2,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "いいちこ辺境伯領",
                        coord: { x:400, z:816},
                        maxZoom: 8,
                        minZoom: 2,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "シーチキン朝",
                        coord: { x:-1303, z:-1256 },
                        maxZoom: 8,
                        minZoom: 2,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "X研究所 スラム砂漠開発支部",
                        coord: { x:-755, z:-1561 },
                        maxZoom: 8,
                        minZoom: 2,
                        info: "",
                        visible: true,
                    },
                    //4
                    {
                        name: "brarth城",
                        coord: { x:-889, z:191 },
                        maxZoom: 8,
                        minZoom: 3,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "鈴蘭台島",
                        coord: { x:255, z:-179 },
                        maxZoom: 8,
                        minZoom: 3,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "ごまの助邸",
                        coord: { x:-1920, z:1659 },
                        maxZoom: 8,
                        minZoom: 3,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "決戦兵器予定地跡地",
                        coord: { "x": -769, "z": -324 },
                        maxZoom: 8,
                        minZoom: 3,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "ポピー島",
                        coord: { "x": -816, "z": -453 },
                        maxZoom: 8,
                        minZoom: 3,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "おしるこ管理島",
                        coord: { "x": -1087, "z": -629 },
                        maxZoom: 8,
                        minZoom: 3,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "骨島",
                        coord: { "x": -1060, "z": -422 },
                        maxZoom: 8,
                        minZoom: 3,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "海洋昆布プラント",
                        coord: { "x": -1405, "z": -156 },
                        maxZoom: 8,
                        minZoom: 3,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "海上林業プラント",
                        coord: { "x": -1051, "z": -39 },
                        maxZoom: 8,
                        minZoom: 3,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "モルチモア大規模トラップ郡",
                        coord: { x:-419, z:-1282 },
                        maxZoom: 8,
                        minZoom: 3,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "チムニー・フォート",
                        coord: { "x": -283, "z": 352 },
                        maxZoom: 8,
                        minZoom: 3,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "スワンプシープ島",
                        coord: { "x": -127, "z": 288 },
                        maxZoom: 8,
                        minZoom: 3,
                        info: "",
                        visible: true,
                    },
                    //5
                    //6
                    {
                        name: "小ポンタ島",
                        coord: { x:-61, z:-29 },
                        maxZoom: 8,
                        minZoom: 4,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "シーチキン公国",
                        coord: { x:-841, z:-1454 },
                        maxZoom: 8,
                        minZoom: 4,
                        info: "未承認国家",
                        visible: true,
                    },
                ]
            }
        ]
    }
];