const points = [
    //world
    {
        name: "main",
        dimensions: [
            {
                type: "overworld",
                points: [
                    {
                        //地名
                        name: "sample",

                        //座標
                        coord: { "x": 0, "z": 0 },

                        //icon画像 default:point
                        icon: "point",

                        //どこまで拡大しても表示するか default:7
                        maxZoom: 6,

                        //どこまで縮小しても表示するか default:0
                        minZoom: 3,

                        //infoウィンドウ(クリックしたら出る)の内容
                        info: "This is a <b>sample</b>",

                        //表示するかどうか
                        visible: true,
                    },
                    {
                        name: "初期リス",
                        coord: { "x": 246, "z": -81 },
                        icon: "waypoint",
                        maxZoom: 7,
                        minZoom: 1,
                        info: "初期リス",
                        visible: true,
                    },
                    {
                        name: "大ポンタ島",
                        coord: { "x": -497, "z": 253 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "対ヒト科決戦兵器",
                        coord: { "x": -769, "z": -324 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "蜘蛛スポナ",
                        coord: { "x": 1277, "z": -1086 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "蜘蛛スポナ―",
                        coord: { "x": -386, "z": -281 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "ゾンビスポナー",
                        coord: { "x": -331, "z": -273 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "ヒトさんち",
                        coord: { "x": -802, "z": -197 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "Nao本島",
                        coord: { "x": -1112, "z": -324 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "おしるこ管理島",
                        coord: { "x": -1087, "z": -629 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "骨島",
                        coord: { "x": -1060, "z": -422 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "ポピー島",
                        coord: { "x": -816, "z": -453 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "アロンシープ島",
                        coord: { "x": -551, "z": -1244 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "デルフォリス号",
                        coord: { "x": -259, "z": 128 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "チムニー・フォート",
                        coord: { "x": -283, "z": 352 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "モルチモア島",
                        coord: { "x": -240, "z": -1022 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "スワンプシープ島",
                        coord: { "x": -127, "z": 288 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "要塞",
                        coord: { "x": -172, "z": 1349 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "ポータル",
                        coord: { "x": -225, "z": 1317 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "九段港湾",
                        coord: { "x": 113, "z": 1139 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "レクト群島",
                        coord: { "x": -1319, "z": -517 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "アラネア島",
                        coord: { "x": -630, "z": -958 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "ブランスラント",
                        coord: { "x": -1244, "z": 341 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "スラム砂漠",
                        coord: { "x": -757, "z": -1537 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "パンダ国",
                        coord: { "x": 689, "z": -526 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "エーリヒクベルク",
                        coord: { "x": -951, "z": 352 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "オルカナキア共和国連合",
                        coord: { "x": -1182, "z": 866 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "納島(仮)",
                        coord: { "x": 269, "z": -257 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "スイレン湾",
                        coord: { "x": -808, "z": 682 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "カルハイド",
                        coord: { "x": -191, "z": 37 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "切裂山",
                        coord: { "x": -297, "z": 612 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "ウルルト",
                        coord: { "x": -324, "z": 546 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "ココド荒野",
                        coord: { "x": 1189, "z": -303 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "シッチー地方",
                        coord: { "x": 99, "z": 639 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "サパンダ",
                        coord: { "x": 811, "z": -388 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "パンダ国駅",
                        coord: { "x": 710, "z": -366 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "stash00",
                        coord: { "x": -1055, "z": -1635 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "レイラン公領",
                        coord: { "x": 473, "z": 1239 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "中書島",
                        coord: { "x": 485, "z": -1207 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "KudakaNina",
                        coord: { "x": 1126, "z": -879 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "みやこハウス",
                        coord: { "x": 95, "z": 575 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "スイレンスブール",
                        coord: { "x": -759, "z": 727 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "おしるこ海洋要塞",
                        coord: { "x": -864, "z": -670 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "シマ半島",
                        coord: { "x": -318, "z": 1569 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "九段大地",
                        coord: { "x": -113, "z": 920 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "うまれえき",
                        coord: { "x": 208, "z": 234 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "KOG島",
                        coord: { "x": -1646, "z": -946 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "最果村",
                        coord: { "x": -1943, "z": 1987 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "test",
                        coord: { "x": -793, "z": -1551 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "デンス村",
                        coord: { "x": -1788, "z": 987 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "マルブール",
                        coord: { "x": -849, "z": 1378 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "stash01",
                        coord: { "x": 266, "z": -85 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "stash05",
                        coord: { "x": -1959, "z": 1868 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "ドロワーズ",
                        coord: { "x": -233, "z": 1691 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "廃墟",
                        coord: { "x": -1415, "z": 1249 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "クノーテン",
                        coord: { "x": -1644, "z": 240 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "海洋昆布プラント",
                        coord: { "x": -1405, "z": -156 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "海上林業プラント",
                        coord: { "x": -1051, "z": -39 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "雲の上",
                        coord: { "x": -438, "z": 1894 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "ガンツ",
                        coord: { "x": -1462, "z": 1604 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "罪の塔",
                        coord: { "x": -1593, "z": 1722 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "魔法都市",
                        coord: { "x": -488, "z": 996 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "天空",
                        coord: { "x": -1812, "z": 1472 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "鶏卵古代文明",
                        coord: { "x": -1525, "z": 1680 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "オルカナキア平原",
                        coord: { "x": -1074, "z": 969 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "グリセンヌ",
                        coord: { "x": -931, "z": 768 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "シメイ地方",
                        coord: { "x": -518, "z": 917 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "OKプレーン",
                        coord: { "x": -1844, "z": -902 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "Pランド",
                        coord: { "x": -1740, "z": 1606 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "アルシア平原",
                        coord: { "x": -1316, "z": 1231 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "ぬこ台地",
                        coord: { "x": 376, "z": 210 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "初期リス平原",
                        coord: { "x": 274, "z": 27 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "謎",
                        coord: { "x": 1169, "z": 1627 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "シットリ半島",
                        coord: { "x": -1338, "z": -1257 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "モノリス",
                        coord: { "x": 747, "z": 36 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "デンス地方",
                        coord: { "x": -1729, "z": 1032 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "Eジプ島",
                        coord: { "x": -1378, "z": -1476 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "クロツェニア",
                        coord: { "x": -1022, "z": 1420 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                    {
                        name: "めいさんち",
                        coord: { "x": -660, "z": 859 },
                        maxZoom: 7,
                        minZoom: 1,
                        info: "",
                        visible: true,
                    },
                ]
            }
        ]
    }
];